"""Add role in User

Revision ID: 29c24601ee56
Revises: 71ff93e29992
Create Date: 2025-04-29 20:51:23.258527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '29c24601ee56'
down_revision: Union[str, None] = '71ff93e29992'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    userrole = postgresql.ENUM('USER', 'ADMIN', name='userrole')
    userrole.create(op.get_bind())
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.Enum('USER', 'ADMIN', name='userrole', create_type=False), server_default='USER', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
    userrole = postgresql.ENUM('USER', 'ADMIN', name='userrole')
    userrole.drop(op.get_bind())
